### ISSUE TITLE
Categorize Leap Bugs in Preparation up through Leap 4.x

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/leap#1440]
Please review the following bugs and categorize them by **adding a comment to the issue**. The suggested categories are 
History
Block Production
Test
API
Peering
Performance
Logging
Transactions
Easy-of-use
Builds
Not-Valid
ABI
Documentation
Snapshots
Not-Classified
Utilities

```[tasklist]
### Tasks
- [ ] https://github.com/AntelopeIO/leap/issues/1149
- [ ] https://github.com/AntelopeIO/leap/issues/1007
- [ ] https://github.com/AntelopeIO/leap/issues/695
- [ ] https://github.com/AntelopeIO/leap/issues/679
- [ ] https://github.com/AntelopeIO/leap/issues/662
- [ ] https://github.com/AntelopeIO/leap/issues/659
- [ ] https://github.com/AntelopeIO/leap/issues/646
- [ ] https://github.com/AntelopeIO/leap/issues/605
- [ ] https://github.com/AntelopeIO/leap/issues/596
- [ ] https://github.com/AntelopeIO/leap/issues/565
- [ ] https://github.com/AntelopeIO/leap/issues/394
- [ ] https://github.com/AntelopeIO/leap/issues/290
- [ ] https://github.com/AntelopeIO/leap/issues/235
```

**Comment by heifner** [comment]
Category comment added to each issue.

**Comment by ericpassmore** [comment]
Thanks reviewed and updated spreadsheet with categories provided
